name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: technote-space/get-diff-action@v6.0.1
        id: git_diff
        with:
          PATTERNS: |
            src/**/**.ts
            test/**/**.ts
            package.json
            yarn.lock

      - name: Install modules
        run: yarn install
        if: env.GIT_DIFF

      - name: Run tests
        run: yarn test
        if: env.GIT_DIFF
